### ISSUE TITLE
Add ORC support

### ISSUE THREAD

**Issue by toprak** [crow-translate/crow-translate#178]
**Is your feature request related to a problem? Please describe**
I am always frustrated when I face words that I do not know while watching movies, tv shows etc. and I want to learn it as quick as possible
**Describe the solution you'd like**
Actually, we can use combination of keys and select text, words with selection border

**Additional context**
You should use tesseract.

**Comment by Shatur95** [comment]
Yes, it would be awesome. But currently I'm out of time, so help is very appreciated.

**Comment by toprak** [comment]
I will ask my friend

**Comment by toprak** [comment]
@yasirtug he said i will add.

**Comment by Shatur95** [comment]
It would be nice. Feel free to ask about project architecture.

**Comment by yasirtug** [comment]
Hi, first of all I should state that I hate you for making this much better than my precious [ni-translate](https://github.com/yasirtug/ni-translate). This is so well written compared to it, to the point that making ni-translate irrelevant :(

Joking, but I will just use crow from now on, and now I am going to add ni-translate's readme to give a shout-out to crow since I will probably abandon it. 

Hopefully my pull request is useful: #179

**Comment by Shatur95** [comment]
xD
Thank you, it's nice that you liked my application!
Your PR is very useful, OCR will be definitely added.
