### ISSUE TITLE
OCR Screen Frame

### ISSUE THREAD

**Issue by kutahyaspor** [crow-translate/crow-translate#269]
**Bug description**
When we drag the surrounding circles to adjust the OCR recognition window after drawing it, the selection screen gets bigger.

**Environment**
-   OS: Ubuntu & Windows
-   Desktop environment: Gnome & Windows 10
-   Crow Translate version: 2.6.2 & 2.7.1

**Additional context**
I showed the problem with a small video;
https://streamable.com/9za442

**Comment by Shatur95** [comment]
Can confirm, thanks.
I'm going to completely replace the screenshot rectangle implementation with the one from Ksnip:
https://github.com/ksnip/ksnip/issues/598

**Comment by Shatur95** [comment]
The author refused to create the library, so we will continue to use the Spectacle's implementation.
But I believe the behavior is correct because the rectangle must be attached to the mouse and the grab points cannot be less than a certain size.
If you disagree, please report the issue to the upstream ([Spectacle](https://invent.kde.org/graphics/spectacle)), because I use this  implementation.
