### ISSUE TITLE
What about telemetry of Google, Yandex and Bing?

### ISSUE THREAD

**Issue by pqks** [crow-translate/crow-translate#32]
When I use Crow Translate, Google, Yandex or Bing(Microsoft) capture some data of my PC? And if so, Is possible delete cookies or something spy tech?

**Comment by Shatur95** [comment]
Crow Translate uses an API to make queries that contain only the text and its parameters. You can check it [here](https://github.com/crow-translate/QOnlineTranslator/blob/38bbacdcfa6e485751115260e177f4dea78064bf/src/qonlinetranslator.cpp#L1156) for Google, [here](https://github.com/crow-translate/QOnlineTranslator/blob/38bbacdcfa6e485751115260e177f4dea78064bf/src/qonlinetranslator.cpp#L1188) for Yandex and [here](https://github.com/crow-translate/QOnlineTranslator/blob/38bbacdcfa6e485751115260e177f4dea78064bf/src/qonlinetranslator.cpp#L1325) for Bing. No other data is captured. Cookies are also not used.

**Comment by VolkMilit** [comment]
Google, Yandex and Bing IS capturing your data even when you write this post. Do you know that GH is owned by Microsoft? 

Also, many sites contains Google telemetry (ADS, counters and so). Using something like Ghostery is not an option, actually, because they will easily track you by installed extensions in your browser. And browser will track you also, don't use Firefox and Chrome(ium) -- they discredit themselves. The only way to be protected (kinda) is mingle with the crowd.

But even if you have 100% resist to all kinds of fingerprints, there is easy way to detect you: IP address and your provider DNS. Your internet provider IS keep logs. 

So, if you worry about your privacy you must use VPN with some sort of DNS on your own private server in another country. And even then you will not be 100% protected, you have no idea how many ways there are to detect a user.

**Comment by pqks** [comment]
> Crow Translate uses an API to make queries that contain only the text and its parameters by GET request for Google and Yandex and by POST for Bing. You can check it here for Google, here for Yandex and here for Bing. No other data is captured. Cookies are also not used. But translation engines can detect your IP.

That's the info what a user need to know.

Thanks for the clarification.

**Comment by Shatur95** [comment]
You are welcome :)
