### ISSUE TITLE
Unresolved dependency libgcc-s1

### ISSUE THREAD

**Issue by stabud** [crow-translate/crow-translate#333]
ubuntu 18.04 + crow-translate_2.8.4_amd64.deb : не устанавливается. Пишет неразрешимая зависимость libgcc-s1
если ставить из репозитария (ppa:jonmagon/crow-translate) , то там старая версия, на которой bing и yandex уже не работают.

**Comment by Shatur** [comment]
The package from releases page compiled under Ubuntu 20.04 because Ubuntu 18.04 have an older version of Tesseract that is not binary compatible with 20.04.

You should compile it yourself or use Appimage from the releases page (it compiled under 18.04 because used tesseract library bundled with the package and doesn't cause issues with never distributions)

**Comment by stabud** [comment]
Спасибо за подсказку! Я собрал и установил новую версию Tesseract и после сумел собрать crow-translate под 18.04.
