### ISSUE TITLE
Yandex translation issue

### ISSUE THREAD

**Issue by abuali129** [crow-translate/crow-translate#35]
I'm trying to use the windows latest version... It is not working when I choose Yandex translation. 
It said
"Error: Engine systems have detected suspicious traffic from your computer network. Please try your request again later."

Google and Bing are working though...

**Comment by Shatur95** [comment]
Is this problem always exists?

**Comment by abuali129** [comment]
Yes, eveytime exit, no matter what language I translate to.

**Comment by abuali129** [comment]
It appears setting input language as auto create this issue with yandex... Manually I put English then no issues faced.

**Comment by Shatur95** [comment]
Just tested it on Windows and Linux and Yandex works. I think that your issue can be caused by your internet provider.
Try to translate with Yandex through proxy. For example, open [Tor Browser](https://www.torproject.org/download/), that configure crow to use Tor proxy (SOCKS5 with 127.0.0.1:9150) and try to translate (Tor Browser window must be opened in background).

**Comment by Shatur95** [comment]
I assume that the issue can be closed.
