### ISSUE TITLE
crow-translate deb package can't install on debian 11

### ISSUE THREAD

**Issue by tmsi-io** [crow-translate/crow-translate#371]
**Bug description**

 crow-translate : Depends: libtesseract4 but it is not going to be installed
                  Recommends: qtgstreamer-plugins-qt5 but it is not going to be installed
                  Recommends: gstreamer1.0-alsa but it is not going to be installed

**Steps to reproduce**

1. download 2.8.7 version amd64 deb file
2. dpkg -i crow-translate_2.8.7_amd64.deb
3.  get 
<pre> crow-translate : Depends: libtesseract4 but it is not going to be installed
                  Recommends: qtgstreamer-plugins-qt5 but it is not going to be installed
                  Recommends: gstreamer1.0-alsa but it is not going to be installed
  </pre>

**Expected behavior**
hope install sucessefull

**Screenshots**

**Environment**

- OS: debian 11 amd64 
- Desktop environment: gnome-3.38.5
- Crow Translate version: 2.8.7

**Additional context**

**Comment by Shatur** [comment]
Please, feel your issue according to the template, I don't understand the problem.

**Comment by Shatur** [comment]
Could you try to remove `gstreamer1.0-alsa` dependency from the package and try to install it again?

**Comment by VolkMilit** [comment]
Just do a `sudo apt install libqt5core5a libqt5dbus5 libqt5gui5 libqt5multimedia5 libqt5network5 libqt5widgets5 libqt5x11extras5 libstdc++6 libtesseract4 libx11-6 libxcb1`, apt will not install already installed packages.

**Comment by VolkMilit** [comment]
Or, you can do a `sudo apt install -f`

**Comment by Shatur** [comment]
I think that we should remove `gstreamer1.0-alsa` because it [doesn't available](https://pkgs.org/search/?q=gstreamer1.0-alsa) in Debian-based systems.
But it unrelated to the issue. As @VolkMilit said, Debian users just need to execute `sudo apt-get -f install` after `dpkg -i <path to .deb>` to install all dependencies. Or use apt directly: `sudo apt install <path to .deb>`.

Let's leave the issue open until `gstreamer1.0-alsa` removal [from CMake](https://github.com/crow-translate/crow-translate/blob/807135c97463e06df927446ca4d8a70af9605331/CMakeLists.txt#L24).
