### ISSUE TITLE
About customize google translate api address

### ISSUE THREAD

**Issue by CylonChau** [crow-translate/crow-translate#480]
Hi contributors

In China CCP banned all Google service, some groups provided Google service proxy. In this circumstances, Is it possible to add something like LiberTraslate feature. allow user configure Google translate api address?

![圖片](https://user-images.githubusercontent.com/29830151/193247068-8b37ef7d-400f-41ad-a177-b55473969bc6.png)

So Chinese users can use it.

**Comment by Shatur** [comment]
Lingva and LibreTranslate have configurable URLs because they have multiple instances. Google Translate have only one instance :(
But you can use Lingva as a replacement because it's basically a proxy over Google Translate (so it's probably exactly what you want). You can read more about it here: https://github.com/thedaviddelta/lingva-translate
We currently doesn't have TTS in Lingva, but it's possible to add it.

**Comment by CylonChau** [comment]
Thank you for your reply
