### ISSUE TITLE
Support aarc64 for windows11

### ISSUE THREAD

**Issue by dhaluza** [crow-translate/crow-translate#502]
Hi!
Please create build for **ARM** windows 11.

**Comment by Shatur** [comment]
The current build for Windows should work on Windows 11.

**Comment by dhaluza** [comment]
> The current build for Windows should work on Windows 11.
yes, works, but i say about **ARM** version Windows and aarch64 architecture CPU. About native operation and not through x86 emulator

**Comment by Shatur** [comment]
Oh, sorry, I misread.
It would be awesome to add builds for Windows ARM (we even already have builds for Linux ARM), but I don't have a device with Windows ARM.
So PRs to setup CI for building for Windows ARM are very welcome.

**Comment by dhaluza** [comment]
im devops and i have thinkpad x13s  with arm windows 11 =) How i can help?

**Comment by Shatur** [comment]
We have a workflow that runs on every release, compiles and uploads the artifacts to the release page:
https://github.com/crow-translate/crow-translate/blob/master/.github/workflows/release.yml
You can add a new entry for Windows Arm and use cross-compilation. It won't be easy, especially on Windows, but should be doable. In order to test runs you can use something like https://github.com/nektos/act or just fork the project, enable GitHub Actions in it and draft dummy releases.

**Comment by dhaluza** [comment]
I have workstation on Linux. I will try. THX for answer.
