### ISSUE TITLE
Add basque language (eu) as available.

### ISSUE THREAD

**Issue by alexgabi** [crow-translate/crow-translate#571]
The basque (eu) translation is at 100% in crowdin.com. Please add it as available language. Thanks.

**Comment by Shatur** [comment]
It was added in https://github.com/crow-translate/crow-translate/releases/tag/2.9.9

**Comment by alexgabi** [comment]
Basque appears in the list of available languages ​​under its original name (euskara) but it doesn't work. In addition, the icon that now accompanies it corresponds to the Spanish language. I send the icon corresponding to Basque.
Thank you.
![ikurriña](https://github.com/crow-translate/crow-translate/assets/6351555/15dc62c0-ebf4-4372-a27c-a59a3a909e7f)

**Comment by Shatur** [comment]
> Basque appears in the list of available languages ​​under its original name (euskara) but it doesn't work.

Oh, I'm sorry. The language option was added, but the translation file was missing. I added it in https://github.com/crow-translate/crow-translate/commit/74bdbdf17274a003339c5cf3aa417e23048f8c3b 3 weeks ago, should appear in the new release. I will draft it soon.

> the icon that now accompanies it corresponds to the Spanish language

I think it happens because I marked the country as Spain: https://github.com/crow-translate/crow-translate/blob/40ac1fcb5190e72c938a6b7d61e35f74509aed95/src/settings/settingsdialog.cpp#L79
And we just take the flag by country:
https://github.com/crow-translate/crow-translate/blob/40ac1fcb5190e72c938a6b7d61e35f74509aed95/src/settings/settingsdialog.cpp#L599-L604
Feel free to contribute, we use [circle-flags](https://github.com/HatScripts/circle-flags/) as icons, the repos is a submodule and icons packed from it.

**Comment by alexgabi** [comment]
Thank you very much, you do a great job. 
The Basque country has a part in Spain and another in France. For that reason we don't identify the language with the Spanish symbol.

**Comment by Shatur** [comment]
> For that reason we don't identify the language with the Spanish symbol.

Makes sense, we probably should use switch for language / locale like we doing https://github.com/crow-translate/crow-translate/blob/65ed73f714aadf682c57bf91c0d23e56ab2cf2b0/src/languagebuttonswidget.cpp#L151
