### ISSUE TITLE
Global shortcut to **translate selected text** is not working

### ISSUE THREAD

**Issue by v1d3rm3** [crow-translate/crow-translate#597]
**Bug description**
Global shortcut to **translate selected text** is not working.

**Steps to reproduce**
1. Open a Website in Edge/Chrome, or open a PDF in Okular
2. Select any text
3. Press Ctrl + Alt + E

**Expected behavior**
Should get a popup with selected text being translated.

**Screenshots**
![Animação](https://github.com/crow-translate/crow-translate/assets/16581931/8f6d4f02-7fce-4fef-a384-8c7b5736a867)

**Environment**

- OS: Windows 10
- Crow Translate version: 2.10.9

**Additional context**
Maybe related with #400?

**Comment by Zelimkhan-Magomadov** [comment]
I also have it on Windows 11. A pop-up window displays the translation of the text that was previously copied (located on the clipboard).

**Comment by Shatur** [comment]
Did this start happening after 2.10.9?

**Comment by pavonz** [comment]
Yes it started happening in version 2.10.9

**Comment by Shatur** [comment]
I think I know why it happens. It's because we started to show main window first to make Wayland on Linux work (it requires to show the window first), but this broke Windows because they don't have a selection buffer and we basically send C-v. Looks like we can't unify this behavior and we will need a condition like it was originally submitted here: https://github.com/crow-translate/crow-translate/pull/596/commits/da55288544e93c824d9127a5c76a322e899f3064

I fill fix it today after work, until then just downgrade to 2.10.7. Or you can send a PR now.

**Comment by akabourek** [comment]
Same problem here:
Manjaro/Arch - flatpak version 2.10.8

**Comment by v1d3rm3** [comment]
Thanks!
