### ISSUE TITLE
Step-by-step guide to enable shortcuts in Ubuntu and other popular Linux distributions

### ISSUE THREAD

**Issue by poglazov** [crow-translate/crow-translate#640]
Despite the mentions of D-Bus and the need to use system level shortcuts, the process for non-developers like myself is not entirely straightforward. So this may limit the user audience.

I might try to make the PR adding to README.md myself. I just want to know if this makes sense.

**Comment by VolkMilit** [comment]
Ubuntu dropped X11?

**Comment by poglazov** [comment]
> Ubuntu dropped X11?

Not sure what you mean, but Wayland is the default since Ubuntu 21.04.

I'm using Ubuntu 22.04.3 LTS and ran into an issue: https://github.com/crow-translate/crow-translate/issues/638. I had heard a little about Wayland, but had no idea how it related to keyboard shortcuts.

I believe that a large portion of Linux users have Ubuntu with Wayland, so I want to make it easier for them to use Crow.

**Comment by Shatur** [comment]
> I believe that a large portion of Linux users have Ubuntu with Wayland

Ubuntu usually at 6-8 place by popularity according to https://distrowatch.com.
While I see the point of step-by-step instruction, it will be different for different DE's. Event Kubuntu and Ubuntu will have different instructions. I would prefer to avoid maintaining it.
I would suggest to blame Wayland for it because it doesn't provide any DE-independent way for global shortcuts.
