### ISSUE TITLE
Add the ability to control the app via CLI

### ISSUE THREAD

**Issue by Jairjua** [crow-translate/crow-translate#73]
I really like this app. The most used feature for me is the text speaking shortcut (control+alt+f). An icon (in Linux panel or above all windows) that speak the translation of the selected text would be more practical than the shortcut.
I don't know if there are some way to create a launcher for a keyboard shortcut on Linux...

**Comment by Shatur95** [comment]
Could you explain your idea a little more?
What do you mean under the icon for speaking?

**Comment by Jairjua** [comment]
By icon I mean "a launcher". Instead of click Control+Alf+F, I would like click at some place. An applet in Linux panel would be nice.

**Comment by Shatur95** [comment]
Unfortunately, I do not think this is possible :(

**Comment by hexauniverse** [comment]
@Shatur95, I'm not completely sure, but I think this is possible if you implement CLI commands for some actions as i suggested in https://github.com/crow-translate/crow-translate/issues/43

I still think it's a good idea because of its universality. Talking about this issue, for instance, you will be able to use [argos](https://github.com/p-e-w/argos) and so on

**Comment by Shatur95** [comment]
Yes, you are right, it will be more universal.
Perhaps I will add the ability to manage the program through console commands.

**Comment by Shatur95** [comment]
Now you can use [D-Bus](https://github.com/crow-translate/crow-translate#d-bus-api), see also #43. It's more standard and universal way.
