### ISSUE TITLE
Add Wikipedia?

### ISSUE THREAD

**Issue by tjesp** [crow-translate/crow-translate#77]
I am not sure if this is outside the scope of what you intend with this but I have a suggestion.

Could you add wikipedia lookups? I find it helpful when I try to 'define' people or places. Especially when I read in foreign languages when there is mention of people or places I am not familiar with.

**Comment by Shatur95** [comment]
Does Wikipedia have an API for this?

**Comment by smaragdus** [comment]
@tjesp 

You can use this very simple Wikipedia look-up tool- **Wikipedia search utility**:

### Links
- [Website](https://w-shadow.com/blog/2006/09/07/wikipedia-search-utility/)
- [Direct Download Link](http://w-shadow.com/files/wsWikiSearch.rar)

### Screen
![Wikipedia search utility 1 0 - 2019-10-29 - 001](https://user-images.githubusercontent.com/9025757/67728279-5a5f2780-f9f5-11e9-9144-62e5282d082a.png)

### Usage
Select a piece of text and press the keyboard shortcut to open/search the related Wikipedia article.

### Note
This is old, tiny (570 KB) and portable tool which still works fine (at least under Windows 8 x64).

**Comment by Shatur95** [comment]
Do I understand correctly, this application simply opens a Wikipedia article?

**Comment by smaragdus** [comment]
@Shatur95 

1. Select a piece of text (word, phrase, name, etc);
2. Execute the keyboard shortcut;
3. The program opens the Wikipedia article (if such exists) in default web browser;

**Comment by Shatur95** [comment]
Hm... It looks like Wiki have an API for [getting](https://www.mediawiki.org/wiki/API:Main_page/en) results, but I think this is beyond the scope of the application.

**Comment by smaragdus** [comment]
@Shatur95 

I find this tool convenient because it works with any program that supports text selection (text editors, mail clients, browsers, office packages, etc).

There are also browser extensions which do the same:

### Chromium-based browsers:

- [Wikipedia Lookup - Context Menu](https://chrome.google.com/webstore/detail/wikipedia-lookup-context/ehigjigpolmdglippjafhnpngmaeepkp)
- [Wikipedia Search](https://chrome.google.com/webstore/detail/wikipedia-search/lipakennkogpodadpikgipnogamhklmk)

### Firefox-based browsers:

- [Wikipedia Context Menu Search](https://addons.mozilla.org/en-US/firefox/addon/wikipedia-context-menu-search/)
- [Wikipedia Easy Search](https://addons.mozilla.org/en-US/firefox/addon/wikipedia-easy-search/)

Yes, there is an [API](https://www.mediawiki.org/wiki/API:Main_page) and yes, I agree that this is beyond the scope of [Crow Translate](https://crow-translate.github.io/). I provided a link to the above mentioned program because for me it useful although it is quite old (from 2006). It is also open source ([direct download link](http://w-shadow.com/files/wsWikiSearch_source.rar), it is written in Delphi).

**Comment by data-man** [comment]
Instead of Wikipedia I propose use Wiktionary.
