### ISSUE TITLE
Selected languages disappear every restart / computer reboot

### ISSUE THREAD

**Issue by the81kid** [crow-translate/crow-translate#88]
Hello, I love the translator! But with this latest version, all the languages I set to translate from/to disappear after restarting the program or restarting my laptop. Is there an option I've missed? Is there a fix I can do my end? Or, should I wait for the next release?

(In any case, good work on this translator! It's very useful.)

**Comment by Shatur95** [comment]
What operating system are you using? I need more needs, because I can not reproduce the bug

**Comment by runo280** [comment]
It happened for me too, I pressed customized key for translation and nothing happened, opened the app's setting and saw my changes gone (like selected langs). But I don't know how to reproduce it yet. Also it's happen for me one time, not on every boot.
Microsoft Windows 10 Pro Build 18363

**Comment by the81kid** [comment]
> What operating system are you using? I need more details, because I can not reproduce the bug

I'm using Linux 19.2. I downloaded and installed the deb file. I don't have much more info to send you. There are no error messages or anything. It just resets to the default/original languages upon computer reboot or program restart. Thanks in advance.

**Comment by Shatur95** [comment]
Could you add languages, then exit Crow Translate through the menu in the system tray icon and start it again?

**Comment by the81kid** [comment]
> Could you add languages, then exit Crow Translate through the menu in the system tray icon and start it again?

Yes. I can add languages each time. But when I restart the computer or the program (after quitting it, or "killing" it), the languages I selected have disappeared.

One thing I need to mention is that I don't have any system tray icons. This seems to be a problem with Linux Mint 19.2 on some computers, which they know about and it's supposed to be fixed in the next release. Other programs also don't have system tray icons, which is a real pain. But Crow Translate is set to start up automatically every time the computer starts, and I have the icon in the Start menu which I can also use to launch it.

**Comment by Shatur95** [comment]
To save the languages ​​you need to close the application properly. When you kill an application, it does not exit normally and languages ​​are not saved. When you turn off the system, the application should exit normally.
I will test it in my VM. What desktop environment are you using? When opening an issue, please provide as many details as possible.

**Comment by the81kid** [comment]
> To save the languages ​​you need to close the application properly. When you kill an application, it does not exit normally and languages ​​are not saved. When you turn off the system, the application should exit normally.
> I will test it in my VM. What desktop environment are you using? When opening an issue, please provide as many details as possible.

I usually never kill the application. Normally I do nothing: Crow Translate starts at bootup, and I turn off the OS without quitting or killing the application. I only "killed" the application twice to test if it would keep the languages if I restarted the application. It made no difference.

I'm using Linux Mint 19.2 Cinnamon. What other details should I give you? I don't receive any error messages or anything. The languages it always starts with are: Greek, Sudanese and Esperanto. This seems a little specific, because they haven't been selected alphabetically or anything. Is it a default setting that it keeps reverting to?

**Comment by Shatur95** [comment]
> What other details should I give you?

I meant that when opening an issue, it is best to write the OS and DE used at least. Thanks, now I get it.

> The languages it always starts with are: Greek, Sudanese and Esperanto. This seems a little specific, because they haven't been selected alphabetically or anything. Is it a default setting that it keeps reverting to?

No, it's weird, the defaults is only "Auto" button...

I tested Linux Mint Cinnamon in VM. Can confirm, the tray icon is missing if the application was launched automatically. If I restart the application, the tray icon appears. Also, the icon appears normally when setting a startup delay. Tested it with other Qt-application and tray icon appears correctly instantly. So, looks like the application bug that appears only in Cinnamon. I will try to fix it.

Languages in Cinnamon ​​are saved normally at logout and are **not** saved at shutdown / reboot (Perhaps the application is killed in this case?). Looks like DE-specific bug. I can't fix it for you :(

**Comment by the81kid** [comment]
Ah, sorry. I understand now. I'm not really a tech guy, although I can find my way around a computer. I should have known to list the OS and relevant info. But, I have some news: I turned on my laptop an hour ago, and Crow Translate has saved my languages from when I set them about hours ago(!). I'm not sure if this is permanent, so I'll keep you posted. Just to add also, all the previous versions of Crow Translate I installed saved the languages. It's only this version that had a problem with it.

The only thing I did different this time when I set the languages last (about 4 hours ago) was I was simultaneously looking inside the /.config/crow/ folder. I opened some of the .conf files with a text editor. But I didn't change/edit anything, and I was never prompted to save any changes when I closed the files. I was comparing some of the language setting numbers in the .conf files with the languages it was resetting to, and with the languages I was trying to set it to (English, German, Spanish). The numbers didn't seem to match any of their positions in the application's language list, but maybe the language numbers aren't in alphabetical order or I didn't read the text right (I'm not a coder).

Regarding the tray icon. Apparently this problem occurs with a lot, maybe most, other applications. On some computers restarting the application will make the application's tray icon appear. But on my system it still doesn't fix the problem. I can't get tray icons for other applications either. From all the forums I've been visiting, it seems to be a problem with this release of Linux Mint (I haven't modded or seriously altered Linux Mint, only installed a few applications/programs). I'm hoping they fix this soon.

By the way, what does the "DE" mean in DE-specific?

**Comment by Shatur95** [comment]
> Just to add also, all the previous versions of Crow Translate I installed saved the languages. It's only this version that had a problem with it.

Could you uninstall this version and check it with the previous one?


> By the way, what does the "DE" mean in DE-specific?

It's **D**esktop **E**nvironment.

**Comment by the81kid** [comment]
Sorry for the late reply. I'm a student, and it was a busy end of the week. Thanks for the definition of DE. I've reinstalled older versions, and they seem to save their languages. I'll write back if the problem returns. It's strange that it suddenly started to work (to save the languages). It didn't work for over a week, then suddenly started working correctly. I hadn't altered anything on my system, or the settings in Crow Translate (apart from select the languages again).

**Comment by Shatur95** [comment]
Ok, glad that everything is working now.

**Comment by Kristinita** [comment]
**Type: Question**

> To save the language you need to close the application properly. When you kill an application, it does not exit normally and languages are not saved.

### 1. Problem

I reproduced the problem on my Windows. It’s no “invalid”.

**If** I closed/restarted Crow Translate via task manager **or** I restarted Windows after BSOD/blackout:

    languages doesn’t save.

**Else** I closed Crow Translate “properly” — via right-click to Crow Translate icon in the taskbar → `Quit`:

    languages saved.

I can add details if needed.

### 2. Question

Is there any reason why you don’t want languages to persist regardless of how Crow Translate is closed?

User add/remove languages → user close `Add language` window → Crow Translate adds languages to configuration file and saves this file → now language will available regardless of how Crow Translate was closed.

Why not does it like this?

Thanks.

**Comment by Shatur** [comment]
> Is there any reason why you don’t want languages to persist regardless of how Crow Translate was closed?

Settings such as the selected language, the languages ​​on the panel, and the size of the window are saved when you exit the application.
It would be resource intensive to update these parameters in the configuration each time they change.
Also, the user can accidentally set a very large number of languages ​​or the size of the window. If the application is killed through the task manager, then these settings will not be saved and it will be expected behavior.
I do not think that BSOD / killing an application is a common case to adapt an application for it.

**Comment by Kristinita** [comment]
**Type: Reply** 💬

I fear that the reply is similar to the defensive behavior (not uncommon for developers), which justifies any acting program behavior, no matter how unfortunate it may be. I hope this is not the case, and you listen to the arguments of the users.

### 1. Replies to arguments

#### 1.1. Resource intensive

> It would be resource intensive to update these parameters in the configuration each time they change.

Could you please provide more details (include technical) how “it would be resource intensive”? I can’t understand how updating the config file can be “resource intensive” to be considered a problem.

#### 1.2. Large number of languages

> Also, the user can accidentally set a very large number of languages

1. What is the problem here? What happens if a user set a many languages?
1. Currently, user also can set a many languages. What’s the difference?

### 2. Problems in current behavior

#### 2.1. It’s not intuitive

Problem with current behavior — it’s not intuitively clear. In all programs that I know, the configuration is saved automatically or via `Save` button (what do you think about `Save` button for Crow Translate?). It isn’t easy to guess that the developer considered it “properly” to save the configuration by when the program closing through the tray.

#### 2.2. How users can close programs

Users don’t necessarily close programs through the tray. For example, see, how I close Crow Translate:

1. Crow Translate 2.8.4 have a bug — sometimes I get multiple Crow Translate windows instead of one. To fix the problem, I open my task manager (Process Hacker) → I select `crow.exe` → `Restart`:

    ![Crow Translate Restart](https://i.imgur.com/l6HJRzD.png)

    It’s faster than closing Crow Translate via tray and waste time to reopen it.

1. Before playing intellectual games tournaments, I close Crow Translate and another programs (this is necessary so as not to be accused of cheating) via [**scripts**](https://gitlab.com/Kristinita/Kiromania). Scripts kill `crow.exe` process and configuration doesn’t save.

Thanks.

**Comment by Shatur** [comment]
> Could you please provide more details (include technical) how “it would be resource intensive”? I can’t understand how updating the config file can be “resource intensive” to be considered a problem.

I/O operations are always slow. If I save settings every time that change frequently (especially window position and language selection!), the application will run much slower. I personally use it on my Linux phone which a potato in case of performance. So the performance is important to me.

> What is the problem here? What happens if a user set a many languages?
> Currently, user also can set a many languages. What’s the difference?

Try to set a large number of languages, then the application may become wider than the screen size. You will not able to edit list of languages without editing registry. I added a small check that checks if the application can fit on the screen, but the check does not work on all platforms (due to the limited API).

> 2.1. It’s not intuitive
> 2.2. How users can close programs

It may not be very intuitive, but users usually do not kill programs through task-managers. I can't adapt the application to every possible use-case. You can just set needed languages and exit the program to save the configuration.

> Scripts kill crow.exe process and configuration doesn’t save.

On Linux, we have a [D-Bus API](https://github.com/crow-translate/crow-translate#d-bus-api) for scripting. It would be nice to have something like this on Windows, but I'm not sure if it exists on this platform.
